[package]
build = "build.rs"
categories = ["api-bindings", "wasm"]
description = "A low-level Rust binding to the zwasm C API, providing FFI access to the zwasm WebAssembly runtime."
documentation = "https://docs.rs/zwasm-sys"
edition = "2021"
license = "MIT"
links = "zwasm"
name = "zwasm-sys"
readme = "README.md"
repository = "https://github.com/zwasm/zwasm-rust-sdk"
version = "0.3.0"
include = [
    "Cargo.toml",
    "LICENSE*",
    "README*",
    "build.rs",
    "src/**/*",
    "zwasm/build.zig",
    "zwasm/build.zig.zon",
    "zwasm/include/**/*",
    "zwasm/src/**/*",
]

[dependencies]

[build-dependencies]
bindgen = { version = "0.72.1", default-features = false, features = [
    "runtime",
] }
